#!/bin/bash

#if you want to build it:
# docker run -v `pwd`:/build-src:ro              ubuntu:xenial /bin/bash /build-src/build-deb-with-docker

# if you want to build it and keep the build result:
# docker run -v `pwd`:/build-src:ro `pwd`:/build ubuntu:xenial /bin/bash /build-src/build-deb-with-docker

set -e
set -x

mkdir -p /build
cp -a /build-src/* /build/
cd /build
ls -l 

[[ -f /tmp/build-deb-with-docker-deps.done ]] || bash -x build-deb-with-docker-deps

ln -s README.md README.txt

python3 setup.py --command-packages=stdeb.command debianize
for file in  debian/* ; do
  echo $file
  [[ -f $file ]] && cat $file
done 

ls -l

# TODO ad package signing for upload: https://searchcode.com/file/115004990/packaging/ubuntu/Makefile

python3 setup.py --command-packages=stdeb.command bdist_deb
find . -name "*.deb"

set +e
dpkg -i deb_dist/python3-consul-lib_0.1.0~dev0-1_all.deb
set -e
apt-get -f install -y
