
name: Integration tests
on:
  - push
jobs:
  Integration-Test-Python:
    name: Integration Tests for Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [35, 36, 38, 310, 312, 314]
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Perform integration tests for python version ${{ matrix.python_version }}
        run: "cd ${{ github.workspace }} && docker compose run --rm integration_tests_py${{ matrix.python_version }}"
